apiVersion: v1
appVersion: v0.0.1
description: Enables Rancher CAPI-based K3s/RKE2 provisioning through the cluster-api-provider-rancher
home: https://github.com/rancher/provisioning/blob/main/chart
kubeVersion: '>= 1.23.0-0'
name: rancher-provisioning
sources:
- https://github.com/rancher/provisioning/blob/main/chart
version: 100.0.0+up0.0.1
